# GitHub Sponsors / Funding links
# These are displayed as a "Sponsor" button on the repository page

github: [jitesh523]
buy_me_a_coffee: jitesh523
custom: ["https://github.com/jitesh523/Aircraft-Engine-Degradation-RUL-Prediction"]
